### ISSUE TITLE
The authority cn.wps.moffice_eng.loader.p.main does not match the one of the contentProvider: com.vspace.proxy_content_provider_0

### ISSUE THREAD

**Issue by ghost** [ALEX5402/NewBlackbox-old#6]
java.lang.SecurityException: The authority cn.wps.moffice_eng.loader.p.main does not match the one of the contentProvider: com.vspace.proxy_content_provider_0
	at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2238)
	at android.content.ContentProvider.validateIncomingUri(ContentProvider.java:2253)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
	at android.os.Binder.execTransactInternal(Binder.java:1028)
	at android.os.Binder.execTransact(Binder.java:1001)

**Comment by ALEX5402** [comment]
> java.lang.SecurityException: The authority cn.wps.moffice_eng.loader.p.main does not match the one of the contentProvider: com.vspace.proxy_content_provider_0 at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2238) at android.content.ContentProvider.validateIncomingUri(ContentProvider.java:2253) at android.content.ContentProvider$Transport.query(ContentProvider.java:238) at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104) at android.os.Binder.execTransactInternal(Binder.java:1028) at android.os.Binder.execTransact(Binder.java:1001)

I am gonna rewriting this whole project into Kotlin, so please keep patience for now ,

Because most of the part of this source is written on java and as we all know continue Kotlin is way easier to manage and readable than java and way more type safe so don't think that i am not closing any issue that does't mean i am not working on that issue nope thats wrong just keep pushing things with proper info with how to recreate that issue again 
so that i can better understand and debug that and i will try my best to fix most of the problems in next build

**Comment by ghost** [comment]
谢谢！
